"""add name field to receipts

Revision ID: 2a16c50171cf
Revises: 651ccf0f65b4
Create Date: 2025-09-17 10:44:59.264487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a16c50171cf'
down_revision: Union[str, Sequence[str], None] = '651ccf0f65b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('receipt_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    connection = op.get_bind()
    
    connection.execute(
        sa.text("""
            UPDATE receipt_table 
            SET name = CASE 
                WHEN raw_data IS NOT NULL AND raw_data != '' THEN raw_data
                ELSE 'Receipt #' || id
            END
        """)
    )
    
    with op.batch_alter_table('receipt_table', schema=None) as batch_op:
        batch_op.alter_column('name', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_table', 'name')
    # ### end Alembic commands ###
