"""add cascade delete to group receipts

Revision ID: 3416f01a1ecd
Revises: 651ccf0f65b4
Create Date: 2025-10-02 12:34:41.312810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3416f01a1ecd'
down_revision: Union[str, Sequence[str], None] = '651ccf0f65b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
